function varargout = cacheCountGUI(hf)
%Create ui
cacheCountFigure = findall(0,'Tag',mfilename);
if isempty(cacheCountFigure)
    % Create a UI
    cacheCountFigure = localCreateUI();
else
    % Bring it to the front
    figure(cacheCountFigure);
end

ad = guidata(hf)

% populate the output if required
if nargout > 0
    varargout{1} = cacheCountFigure;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function to create the user interface
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function cacheCountFigure = localCreateUI()
% Create the figure, setting appropriate properties
cacheCountFigure = figure('Tag',mfilename,...
                        'Toolbar','none',...
                        'MenuBar','none',...
                        'IntegerHandle','off',...
                        'Units','normalized',...
                        'Resize','on',...
                        'NumberTitle','off',...
                        'HandleVisibility','callback',...
                        'Name',sprintf('Cache count'),...
                        'Visible','on');
                    
% Create an axes on the figure
cacheCountAxes = axes('Parent',cacheCountFigure,...
    'HandleVisibility','callback',...
    'Unit','normalized',...
    'OuterPosition',[0.25 0.1 0.75 0.8],...
    'Xlim',[0 10],...
    'YLim',[0 20],...
    'Tag','plotAxes');
xlabel(cacheCountAxes,'Time');
ylabel(cacheCountAxes,'Cache counts');
title(cacheCountAxes,'Cache count v''s Time');
grid(cacheCountAxes,'on');
box(cacheCountAxes,'on');
    