function varargout = CycleTimeGUI(hf)
%Laod application data
ad = guidata(hf);

%Create ui
cycleTimeFigure = findall(0,'Tag',mfilename);
if isempty(cycleTimeFigure)
    % Create a UI
    cycleTimeFigure = localCreateUI(ad);
else
    % Bring it to the front
    figure(cycleTimeFigure);
end

% populate the output if required
if nargout > 0
    varargout{1} = cycleTimeFigure;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function to create the user interface
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function cycleTimeFigure = localCreateUI(ad)
% Create the figure, setting appropriate properties
cycleTimeFigure = figure('Tag',mfilename,...
                        'Toolbar','none',...
                        'MenuBar','none',...
                        'IntegerHandle','off',...
                        'Units','normalized',...
                        'Resize','on',...
                        'NumberTitle','off',...
                        'HandleVisibility','callback',...
                        'Name',sprintf('Cycle time'),...
                        'Visible','on');
                    
% Create an axes on the figure
cycleTimeAxes = axes('Parent',cycleTimeFigure,...
    'HandleVisibility','callback',...
    'Unit','normalized',...
    'OuterPosition',[0.25 0.1 0.75 0.8],...
    'Xlim',[0 10],...
    'YLim',[0 30],...
    'Tag','plotAxes');
xlabel(cycleTimeAxes,'Time');
ylabel(cycleTimeAxes,'Cycle time');
title(cycleTimeAxes,'Cycle time v''s Time');
grid(cycleTimeAxes,'on');
box(cycleTimeAxes,'on');

%Add line for average cycle time
avgCycleTimeLineHandle = line('Parent',cycleTimeAxes,...
        'XData',[],...
        'YData',[],...
        'Color', 'black',...
        'EraseMode','xor',...
        'Tag',sprintf('Cycle time'));

cycleTimeFigure.avgCycleTimeHandle = avgCycleTimeLineHandle;

%Add array to save individual production
numberOfLines = length(ad.lineHandles);
cycleTimeFigure.individualCycleTimes = zeros(1, numberOfLines);
    
